{
    'name':'ITI_Mans_2',
    'author':'reem',
    'website':'https://iti.gov.eg/',
    'version':'0.1',
    'application':'True',
    'data':['views/iti_student_views.xml','views/iti_track_views.xml'
            ],
}